version: "3.1"
services:
  whiteboard:
    image: rofl256/whiteboard
    restart: always
    ports:
      - "8080:8080/tcp"
    command: --config=./config.default.yml
    environment:
      - REDIS_HOST=redis-cache-1.h5vflu.ng.0001.euw2.cache.amazonaws.com
      - REDIS_PORT=6379
    volumes:
      - ./data/uploads:/opt/app/public/uploads
      - ./data/config.yml:/opt/app/config.default.yml:ro
      - ./data/savedBoards:/opt/app/savedBoards